---
title: "Plot gemiddeld aantal bezoekers per dag"
author: "D.R. Cirkel"
date: "14 juni 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars, include=FALSE}

library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(leaflet)
library(viridis)
library(lubridate)
library(reshape2)
### Load data 
wifidf.orig <- read_csv2("~/Kennisnetwerk/Wifipunten/locatus/locatusdata_bewerkt.csv", trim_ws = TRUE)

gps_locaties_sensors <- read_csv2("~/Kennisnetwerk/Wifipunten/locatus/gps_locaties_sensors.csv",  trim_ws = TRUE)

```
```{r transformations, include = FALSE}

### Change some things, join dfs
wifidf <- wifidf.orig %>%
  drop_na(DateTimeLocal) %>%
  rename(ID =VirtualSensorCode) %>%
  left_join(gps_locaties_sensors)  %>%
  mutate(Date = as.Date(DateTimeLocal), 
         Time = format(DateTimeLocal, "%H:%M:%S"), 
         Kwart = format(round_date(DateTimeLocal, "15 minutes"), "%H:%M"))

# Calculate average count per weekday
wifidf.wkdy <- wifidf %>%
  mutate(wkdy = weekdays(DateTimeLocal)) %>%
  group_by(ID, lat, lon, wkdy, Date) %>%
  summarise(count = n()) %>%
  summarize(avg = mean(count)) %>%
  mutate(wkdy = factor(wkdy, levels =c("maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag")))
```


```{r plot, echo=FALSE, out.width = '120%'}

# Plot voor gemiddeld aantal bezoekers per dag van de week 
pal <- leaflet::colorFactor(viridis_pal(option = "D")(20), domain = c(0:10000)) 

map = leaflet(data = wifidf.wkdy) %>%
  addTiles() %>% 
  addProviderTiles(providers$OpenStreetMap)

for(w in levels(wifidf.wkdy$wkdy)){
  d = wifidf.wkdy[wifidf.wkdy$wkdy == w,]
  map = map %>% addCircleMarkers(data = d,
                                 lat = ~lat, 
                                 lng = ~lon, 
                                 radius = ~sqrt(avg)/5,
                                 color = ~pal(round(avg,0)), 
                                 label = ~as.character(round(avg,0)), 
                                 popup = ~as.character(round(avg,0)), 
                                 opacity = 0.8,
                                 fillOpacity = 0.6,
                                 group = w,
                                 labelOptions = labelOptions(noHide = T))
}

map %>% addLayersControl(baseGroups = factor(wifidf.wkdy$wkdy, levels =c("maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag")),
                         options = layersControlOptions(collapsed = FALSE, sortLayers = TRUE)) %>%
  addLegend("bottomright", pal = pal, values = seq(from = 10000,to = 0, by = -1000),
            title = "Gemiddeld aantal bezoekers") 

```
